version: '3'
services:
  influxdb:
    image: influxdb:1.7-alpine
    environment:
      - INFLUXDB_DB=jmeter
      - INFLUXDB_CONFIG_PATH=/tmp/influx.conf
    ports:
      - '2003:2003' #Graphite
      - '8086:8086' #Influx API
    volumes:
      - ./docker/influxdb/influx.conf:/tmp/influx.conf

  jmeter:
    build:
      context: .
      dockerfile: docker/jmeter/Dockerfile
      args:
        - jmeterVersion=5.2
    environment:
      - JMETER_TEST=test.jmx
      - JMETER_WEBURL=http://127.0.0.1:7001
      - JMETER_THREADS=100
      - JMETER_DURATION=60
      - JMETER_RAMPUP=10
    volumes:
      - ./docker/jmeter/test:/jmeter/test/
    depends_on:
      - influxdb

  grafana:
    build:
      context: .
      dockerfile: docker/grafana/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel
    volumes:
      - ./docker/grafana/dashboards/jmeter.json:/var/lib/grafana/dashboards/jmeter.json
    depends_on:
      - influxdb
      - jmeter
